# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('image', '0002_image_comments_count'),
        ('user', '0005_remove_userprofile_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Create time')),
                ('likes_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('text', models.TextField(default='')),
                ('attachments', models.ManyToManyField(related_name='post', to='image.Image')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='user.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
