# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 20:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20160929_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
