# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-12 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='post', to='image.Image'),
        ),
    ]
