# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 13:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0006_friendship'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('type', models.CharField(choices=[('C', 'Create'), ('U', 'Update')], max_length=1)),
                ('e_item_id', models.PositiveIntegerField()),
                ('e_item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='contenttypes.ContentType')),
                ('users', models.ManyToManyField(related_name='event', to='user.UserProfile')),
            ],
            options={
                'verbose_name_plural': 'Events',
                'verbose_name': 'Event',
            },
        ),
    ]
