# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 15:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='e_item_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='e_item_type',
            new_name='item_type',
        ),
    ]
