# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20160929_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='type',
            new_name='action_type',
        ),
    ]
