# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Create time')),
                ('likes_count', models.IntegerField(default=0)),
                ('file', models.ImageField(upload_to='', verbose_name='File')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
