# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
    ]
