# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_friendship'),
        ('image', '0002_image_comments_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='user.UserProfile'),
            preserve_default=False,
        ),
    ]
