# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 03:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Create time')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('P', 'Prefer not to answer')], default='P', max_length=1)),
                ('avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image', verbose_name='Avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'User profiles',
                'verbose_name': 'User profile',
            },
        ),
    ]
