# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20160929_0324'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
