# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_userprofile_likes_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_requests', to='user.UserProfile')),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='me_requests', to='user.UserProfile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
