# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20160929_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='user.UserProfile', verbose_name='User'),
        ),
    ]
