# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 04:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20160929_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='object_id',
            new_name='item_id',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='content_type',
            new_name='item_type',
        ),
    ]
