# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 14:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_friendship'),
        ('comment', '0005_auto_20160929_0437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user_author',
        ),
        migrations.AddField(
            model_name='comment',
            name='comments_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='user.UserProfile'),
            preserve_default=False,
        ),
    ]
