# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 03:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Create time')),
                ('item_id', models.PositiveIntegerField()),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.UserProfile', verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Likes',
                'verbose_name': 'Like',
            },
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set([('user', 'item_type', 'item_id')]),
        ),
    ]
